//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MM.rc
//
#define ID_SAVE_PARAMETERS              3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MM_DIALOG                   102
#define IDR_MAINFRAME                   128
#define IDR_MENU1                       129
#define IDR_MENU_TOP                    129
#define IDD_PANEL_CREATE                130
#define IDD_PANEL_MODIFY                131
#define IDI_NEW                         132
#define IDD_PANEL_STATE                 136
#define IDR_ACCELERATOR1                143
#define IDI_UNDO                        144
#define IDI_REDO                        145
#define IDI_SELECT                      148
#define IDI_MOVE                        150
#define IDI_SIZE                        151
#define IDI_ROTATE                      152
#define IDD_CUBOID                      153
#define IDD_CYLINDER                    154
#define IDD_SPHERE                      155
#define IDD_CONE                        156
#define IDD_TORUS                       157
#define IDD_PIPE                        158
#define IDR_MENU_POPUP                  159
#define IDI_OPEN                        161
#define IDI_SAVE                        162
#define IDI_OUTPUT                      163
#define IDD_OUTPUT                      164
#define IDC_FRONTVIEW                   1000
#define IDC_LEFTVIEW                    1001
#define IDC_UPVIEW                      1002
#define IDC_VIEW                        1003
#define IDC_TAB1                        1004
#define IDC_UNDO                        1005
#define IDC_REDO                        1006
#define IDC_SELECT_MOVE                 1007
#define IDC_SELECT                      1008
#define IDC_ALL                         1009
#define IDC_NEWFILE                     1010
#define IDC_SELECT_SIZE                 1011
#define IDC_POSITION                    1012
#define IDC_ROTATE                      1012
#define IDC_OPEN                        1013
#define IDC_CONE                        1014
#define IDC_SAVE                        1014
#define IDC_EDIT_DESITY                 1015
#define IDC_SPHERE                      1015
#define IDC_PARALLEL_MOVE               1015
#define IDC_OUTPUT                      1015
#define IDC_SLIDER_DESITY               1016
#define IDC_IMPORT                      1016
#define IDC_SLIDER_MOVE                 1016
#define IDC_CYLINDER                    1017
#define IDC_TORUS                       1018
#define IDC_CHANGE_VIEWSTYLE            1019
#define IDC_PIPE                        1019
#define IDC_LIST_CREATE                 1022
#define IDC_NEW_SCENE                   1023
#define IDC_CS_LIST                     1024
#define IDC_LISTCS                      1025
#define IDC_COLOR                       1027
#define IDC_NAME                        1028
#define IDC_COMBO_TYPES                 1029
#define IDC_CUBOID                      1031
#define IDC_RADIO_CUBE                  1033
#define IDC_KB_X                        1034
#define IDC_KB_Y                        1035
#define IDC_KB_Z                        1036
#define IDC_KB_LENGTH                   1037
#define IDC_PARA_X                      1037
#define IDC_KB_IR                       1037
#define IDC_KB_WIDTH                    1038
#define IDC_PARA_Z                      1038
#define IDC_KB_HEIGHT                   1039
#define IDC_PARA_Y                      1039
#define IDC_KB_CREATE                   1040
#define IDC_PARA_AREA                   1041
#define IDC_PARA_LENGTH                 1042
#define IDC_PARA_WIDTH                  1043
#define IDC_PARA_HEIGHT                 1044
#define IDC_RADIO_CUBOID                1045
#define IDC_LIST_NX                     1053
#define IDC_LIST_NY                     1054
#define IDC_REGULAR_POLYGON             1054
#define IDC_LIST_NZ                     1055
#define IDC_NORMAL_POLYGON              1055
#define IDC_CIRCLE                      1056
#define IDC_KB_R                        1057
#define IDC_LIST_DN                     1058
#define IDC_PARA_R                      1059
#define IDC_LIST_NR                     1063
#define IDC_LIST_NH                     1064
#define IDC_LIST_NJ                     1065
#define IDC_LIST_N                      1065
#define IDC_LIST_NW                     1066
#define IDC_KB_INNER_R                  1067
#define IDC_PARA_INNER_R                1069
#define IDC_POINT_CHOOSE                1072
#define IDC_BOX_CHOOSE                  1073
#define IDC_START_DRAG                  1077
#define IDC_START_DISSECT               1078
#define IDC_START_DENSIFY               1079
#define IDC_POINT_SIZE                  1080
#define IDC_CURSOR_BOX                  1081
#define IDC_CURSOR_WIDTH                1082
#define IDC_CURSOR_HEIGHT               1083
#define IDC_MOVE                        1084
#define IDC_KNIFE_RATIO                 1085
#define IDC_KNIFE_SIZE                  1086
#define IDC_3POINTS_KNIFE               1087
#define IDC_CUT                         1088
#define IDC_NUM_HASPICKED               1089
#define IDC_DENSIFY_CHOOSED             1090
#define IDC_DENSIFY                     1091
#define IDC_START_MERGE                 1092
#define IDC_IX                          1094
#define IDC_IY                          1095
#define IDC_L                           1096
#define IDC_W                           1097
#define IDC_H                           1098
#define IDC_SIZE                        1099
#define IDR_MENU_FILE_OPEN              32771
#define IDR_MENU_FILE_SAVE              32772
#define IDR_MENU_FILE_EXIT              32773
#define IDR_MENU_EDIT_UNDO              32774
#define IDR_MENU_EDIT_REDO              32775
#define ID_HIDE                         32780
#define ID_SHOW_ALL                     32781
#define ID_FREEZE                       32782
#define ID_FREE                         32783
#define ID_DELETE_OBJECT                32784
#define ID_COPY                         32785
#define ID_PASTE                        32786
#define ID_EXPORT_CS                    32787
#define ID_EDIT_THIS                    32788

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        165
#define _APS_NEXT_COMMAND_VALUE         32789
#define _APS_NEXT_CONTROL_VALUE         1095
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
